### ISSUE TITLE
mly.set_token(MLY_ACCESS_TOKEN) missing at Colab Demo

### ISSUE THREAD

**Issue by kauevestena** [mapillary/mapillary-python-sdk#143]
First of all, congrats for the API!!

I was trying to test the demo when I realized that the mentioned line was missing at the notebook!!

It may be putted right after the "MLY_ACCESS_TOKEN" declaration at the third jupyter cell!

Best Regards,
Kauê

**Comment by Rubix982** [comment]
Thank you, @kauevestena for that!

Edited in the notebook.

Closing issue.

![image](https://user-images.githubusercontent.com/41635766/180595274-88a72811-418a-400b-9b39-ff830ab1cb05.png)
