### ISSUE TITLE
Create documentation draft

### ISSUE THREAD

**Issue by cbeddow** [mapillary/mapillary-python-sdk#6]
We need a folder in the main/root directory called "docs".

Sign up for an account at: https://readthedocs.org/

We should then use the following instructions to generate documentation with Mkdocs: https://docs.readthedocs.io/en/stable/intro/getting-started-with-mkdocs.html

We need to somehow create the docs then attempt to import to read the docs.

The generated documentation will go in the docs folder.

It should look similar to the setup in OSMnx library here: https://github.com/gboeing/osmnx

And we can model after the OSMnx library docs: https://osmnx.readthedocs.io/en/stable/

**Comment by Rubix982** [comment]
In progress. The tool has been changed to Docusaurus.

**Comment by Rubix982** [comment]
Assigning to @OmarMuhammedAli
